# SPDX-FileCopyrightText: 2021 Romain Porte <microjoe@microjoe.org>
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[workspace]
members = [
    "gladis",
    "gladis_proc_macro",
]

# Only tag and update CHANGELOG once during `gladis` crate upload
[workspace.metadata.release]
disable-tag = true
