# SPDX-FileCopyrightText: 2021 Agathe Porte <microjoe@microjoe.org>
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

# configuration file for git-cliff (0.1.0)

[changelog]
# changelog header
header = """
<!--
SPDX-FileCopyrightText: 2022 Agathe Porte <microjoe@microjoe.org>

SPDX-License-Identifier: Apache-2.0 OR MIT
-->

# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

<!-- next-header -->
"""
# template for the changelog body
# https://tera.netlify.app/docs/#introduction
body = """
{% if version %}\
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else %}\
    ## [unreleased]
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
# remove the leading and trailing whitespaces from the template
trim = true
# changelog footer
footer = """
## [1.0.1] - 2021-09-20

### Added

- New example of use with the Relm crate.
- Use [cargo-release](https://github.com/crate-ci/cargo-release) for release
  handling.

## [1.0.0] - 2021-07-05

### Added

- Simple example of use.
- Automated build and test based on Github Actions.

### Changed
- Updated both crates to depend on gtk (gtk-rs) 0.14 (previously was: 0.4.1).

## [0.4.1] - 2020-08-08

### Added
- Implement Display + Error for error types.
- Fix clippy lints

## [0.4.0] - 2020-07-30

### Added

- Proper error handling.

### Changed

- Fixed missing automatic derive import.
- Implement trivial functions in the trait directly instead of in the macro.

### Removed

- Now useless mention of the `gladis_proc_macro` crate in README.

## [0.3.1] - 2020-07-30

### Changed

- Fixed wrong version example in README.md.

## [0.3.0] - 2020-07-30

### Changed

- Changed license from Apache 2 to dual licensed Apache 2 + MIT to be compatible
  with GPLv2 software.
- Regrouped `gladis` and `gladis_proc_macro` under the same repository using
  Cargo workspace.

## [0.2.1] - 2020-07-19

### Added

- Basic documentation with doctests.

## [0.2.0] - 2020-07-16

### Changed

- Renamed `from_glade_src` to `from_string` to match the gtk::Builder function
  names.
- Updated README with a new example.

## [0.1.2] - 2020-07-14

### Added

- New `from_resource` and `from_builder` functions.
- New dependency to gtk as it is now necessary for `from_builder`
  prototype.

## [0.1.1] - 2020-07-14

### Changed

- Fix wrong repository link in Cargo.toml.

## [0.1.0] - 2020-07-14

- Initial release.

<!-- generated by git-cliff -->
"""

[git]
# parse the commits based on https://www.conventionalcommits.org
conventional_commits = true
# filter out the commits that are not conventional
filter_unconventional = true
# regex for parsing and grouping commits
commit_parsers = [
    { message = "^.*: add", group = "Added"},
    { message = "^.*: support", group = "Added"},
    { message = "^.*: remove", group = "Removed"},
    { message = "^.*: delete", group = "Removed"},
    { message = "^test", group = "Fixed"},
    { message = "^fix", group = "Fixed"},
    { message = "^.*: fix", group = "Fixed"},
    { message = "^.*", group = "Changed"},
]
# filter out the commits that are not matched by commit parsers
filter_commits = true
# glob pattern for matching git tags
tag_pattern = "v[0-9]*"
# regex for skipping tags
skip_tags = "v0.1.0|v0.1.1|v0.1.2|v0.2.0|v0.2.1|v0.3.0|v0.3.1|v0.4.0|v0.4.1|v1.0.0|v1.0.1"

# regex for ignoring tags
ignore_tags = ""
# sort the tags topologically
topo_order = false
# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"

