# SPDX-FileCopyrightText: 2021 Agathe Porte <microjoe@microjoe.org>
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

consolidate-commits = true
shared-version = true
consolidate-pushes = true
allow-branch = ["master"]
disable-tag = true
