pre-release-commit-message = "release {{version}}"
disable-tag = false
tag-message = "{{tag_name}}"
tag-name = "v{{version}}"
sign-tag = true
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}"},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}"},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate", exactly=1},
  {file="README.md", search="gladis = .*", replace="{{crate_name}} = \"{{version}}\""},
]
